language: java

jdk:
  - openjdk11

branches:
  only:
    - development
    - main

before_script:
  - ls -la

script:
  - mvn clean package
  - mvn package jacoco:report
after_success:
  - echo "Process terminated successfully."